name: 'docker build action'
description: 'docker build action'
inputs:
  context:  
    description: 'context'
    required: true
    default: '.'
  tags:  
    description: 'tags'
    required: true
    default: ''
  build-from:  
    description: 'build from'
    required: false
    default: ''
  force-build:
    description: 'whether force build image'
    required: false
    default: false
outputs:
  imageid:
    description: 'Image ID'
    value: ${{ steps.build-and-push.outputs.imageid }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build-and-push.outputs.digest }}
  metadata:
    description: 'Build result metadata'
    value: ${{ steps.build-and-push.outputs.metadata }}

runs:
  using: "composite"
  steps:
    - name: check required env variables
      if: ${{ (env.GH_ACT_LAEBLS == '') || ( env.DOCKER_IMAGE_FULL_BASE == '') }}
      run: |
        echo "Please check the environment variables:"
        echo env.GH_ACT_LAEBLS=${env.GH_ACT_LAEBLS}
        echo env.DOCKER_IMAGE_FULL_BASE=${env.DOCKER_IMAGE_FULL_BASE}
        exit 1
      shell: bash
    
    - run: |
        echo "Prepare to build image with tags: ${{ inputs.tags }}"
      shell: bash

    - id: check-arg
      run: |
         [ "${{ inputs.build-from }}" != "" ] ||  echo "from_flag=" >> $GITHUB_OUTPUT
         [ "${{ inputs.build-from }}" == "" ] ||  echo "from_flag=from=${{ inputs.build-from }}" >> $GITHUB_OUTPUT

         context_folder=$(echo "${{inputs.context}}" | sed 's/\/$//')
         echo "context_folder="${context_folder}"" >> $GITHUB_OUTPUT

         echo "context_folder="${context_folder}"" >> $GITHUB_OUTPUT
      shell: bash
    
    - run: |
        echo "${{ steps.check-arg.outputs.context_folder }}"
      shell: bash
    - run: |
        echo "${{ env.GH_ACT_MODIFIED_FILES }}"
      shell: bash
    - run: |
        echo "${{ env.GH_ACT_META_JSON }}"
      shell: bash

    - id: build-and-push
      uses: docker/build-push-action@v3
      if: env.FORCE_BUILD_FLAG || inputs.force-build || contains(env.GH_ACT_MODIFIED_FILES, steps.check-arg.outputs.context_folder)
      with:
        push: ${{ env.WITH_PUSH == 'true' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: |
          ${{ env.GH_ACT_LAEBLS }}
          con.image.build-from=${{ inputs.build-from }}
          con.image.dockerfile.${{steps.check-arg.outputs.context_folder}}.created=${{ fromJSON(env.GH_ACT_META_JSON).labels['org.opencontainers.image.created'] }}
          con.image.dockerfile.${{steps.check-arg.outputs.context_folder}}.version=${{ fromJSON(env.GH_ACT_META_JSON).labels['org.opencontainers.image.version'] }}
          con.image.dockerfile.${{steps.check-arg.outputs.context_folder}}.revision=${{ fromJSON(env.GH_ACT_META_JSON).labels['org.opencontainers.image.revision'] }}
        context: ${{ inputs.context }}
        tags: ${{ inputs.tags }}
        build-args: ${{ steps.check-arg.outputs.from_flag }}
    
